name: iOS Dev Build

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'ios-dev-*'  # Trigger on any tag with 'ios-dev-'

jobs:
  build-ios-dev:
    name: Build and Upload iOS Dev
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --debug --no-codesign
        if: startsWith(github.ref, 'refs/tags/ios-dev')

      - name: Upload iOS Dev IPA to GitHub Release
        if: startsWith(github.ref, 'refs/tags/ios-dev')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/Runner.app
          tag: ${{ github.ref_name }}
          overwrite: true
          body: "iOS dev build for ${{ github.ref_name }}"
